In [7]:
!pip install transformers

     |████████████████████████████████| 2.3MB 4.9MB/s 
     |████████████████████████████████| 901kB 24.2MB/s 
     |████████████████████████████████| 3.3MB 37.1MB/s 


In [8]:
# Importing required modules
import torch
from transformers import BertTokenizer, BertModel

In [11]:
# Importing required modules
import logging
import matplotlib.pyplot as plt

In [12]:
# Loading model tokenizer(pre-trained)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [31]:
# Random text for testing
text = "BERT is being used to generate embeddings of the input text."
# Adding the [CLS] and [SEP] markers
marked_text = "[CLS] " + text + " [SEP]"

In [32]:
# Tokenizing the random text for testing purpose
tokenized_text = tokenizer.tokenize(marked_text)
print (tokenized_text)

['[CLS]', 'bert', 'is', 'being', 'used', 'to', 'generate', 'em', '##bed', '##ding', '##s', 'of', 'the', 'input', 'text', '.', '[SEP]']


In [33]:
list(tokenizer.vocab.keys())[5000:5020]

['knight',
 'lap',
 'survey',
 'ma',
 '##ow',
 'noise',
 'billy',
 '##ium',
 'shooting',
 'guide',
 'bedroom',
 'priest',
 'resistance',
 'motor',
 'homes',
 'sounded',
 'giant',
 '##mer',
 '150',
 'scenes']

In [51]:
# Random text used for testing 
text = "As he crossed toward the pharmacy at the corner he involuntarily turned "\
       "his head because of a burst of light that had ricocheted from his temple, "\
       "and saw, with that quick smile with which we greet a rainbow or a rose, a "\
       "blindingly white parallelogram of sky being unloaded from the van."
    
marked_text = "[CLS] " + text + " [SEP]"

In [37]:
# Tokenizing the text for testing BERT
tokenized_text = tokenizer.tokenize(marked_text)

In [38]:
# Map the token strings to their vocabulary indeces
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)

In [39]:
# Displaying the words in the text with their indices
for tup in zip(tokenized_text, indexed_tokens):
    print('{:<12} {:>6,}'.format(tup[0], tup[1]))

[CLS]           101
as            2,004
he            2,002
crossed       4,625
toward        2,646
the           1,996
pharmacy     13,882
at            2,012
the           1,996
corner        3,420
he            2,002
in            1,999
##vo          6,767
##lun        26,896
##tar         7,559
##ily         6,588
turned        2,357
his           2,010
head          2,132
because       2,138
of            1,997
a             1,037
burst         6,532
of            1,997
light         2,422
that          2,008
had           2,018
rico          7,043
##chet       20,318
##ed          2,098
from          2,013
his           2,010
temple        3,379
,             1,010
and           1,998
saw           2,387
,             1,010
with          2,007
that          2,008
quick         4,248
smile         2,868
with          2,007
which         2,029
we            2,057
greet        17,021
a             1,037
rainbow      10,098
or            2,030
a             1,037
rose          3,123


In [40]:
# Marking each of the tokens as belonging to sentence "1"
segments_ids = [1] * len(tokenized_text)
print (segments_ids)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [41]:
# Converting input text to Pytorch tensors
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

In [42]:
# Load pre-trained model
model = BertModel.from_pretrained('bert-base-uncased',
                                  output_hidden_states = True,
                                 )
# Putting the model in "evaluation" mode
model.eval()

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          

In [49]:
# Feeding the random text to the BERT model for generating hidden states (embeddings)
with torch.no_grad():
  outputs = model(tokens_tensor, segments_tensors)
  hidden_states = outputs[2]

In [50]:
# Displaying the generated embeddings of the input text
hidden_states

(tensor([[[ 0.1686, -0.2858, -0.3261,  ..., -0.0276,  0.0383,  0.1640],
          [ 0.1063,  0.5802, -0.3213,  ...,  0.5853,  0.9010,  0.4799],
          [-0.3368,  0.1523,  0.4105,  ..., -0.1731, -0.2439,  0.2569],
          ...,
          [ 0.7324, -0.5857,  0.1327,  ..., -1.1664,  0.4797,  1.4680],
          [-0.2773,  0.2856,  0.0226,  ...,  0.1520,  0.5982,  0.7719],
          [-0.6079, -0.0166,  0.3581,  ..., -0.5859,  0.4797,  0.1967]]]),
 tensor([[[ 0.0179,  0.0588, -0.2825,  ...,  0.1973, -0.0611,  0.0506],
          [ 0.0694,  0.5924, -0.6214,  ...,  0.4202,  0.7229,  0.2569],
          [-0.3269,  0.4205,  0.5472,  ..., -0.6306, -0.1368,  0.3181],
          ...,
          [ 1.1337, -0.4102, -0.3835,  ..., -1.2925,  0.3478,  1.1074],
          [-0.0455, -0.1745, -0.2060,  ...,  0.0671,  0.2721,  0.6590],
          [-0.4384, -0.0484,  0.0419,  ..., -0.4106,  0.3411,  0.1869]]]),
 tensor([[[-0.1348, -0.0942, -0.4027,  ...,  0.2463,  0.1710, -0.0596],
          [ 0.0021,  0.8881,